---
title: "Data Gathering"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library(tidycensus)
library(leaflet)
library(lubridate)
library(stringr)
library(rstanarm)
library(naniar)
library(tidymodels)
library(ggthemes)
library(gtsummary)
library(broom.mixed)
library(gt)
```

Initial Cleaning of ACLED Data
```{r}
acled_data_new <- read_xlsx("raw_data/protest_data.xlsx") %>%
  clean_names() %>%
  mutate(assoc_actor_1 = as.factor(assoc_actor_1),
         event_type = as.factor(event_type),
         sub_event_type = as.factor(sub_event_type)) %>%
  
  # Because the column names given in the original dataset were not clean, I 
  # manually changed the col_types using mutate(). 
  
  filter(!event_type == "Strategic developments") %>%
  
  # This project focuses on protests — 'strategic developments' are interesting
  # but ultimately irrelevant.
  
  mutate(event_date = ymd(event_date)) %>%
  select(-c(iso, event_id_cnty, event_id_no_cnty, year, time_precision, region, 
            country, admin3, geo_precision, source_scale, source, inter1,
            inter2, interaction)) %>%
  mutate(assoc_actor_1 = as.character(assoc_actor_1)) %>%
  rename("county" = admin2) %>%
  transform("county" = paste(county, admin1, sep = ", "))

# I pasted together county and state because there are many counties with
# identical names in different states.
```

Prepping ACLED Data for Violence Modeling
```{r}
acled_modeling <- acled_data_new %>%
  mutate(violence = ifelse(sub_event_type == "Peaceful protest", 
                           yes = FALSE, no = TRUE))

# The ACLED data categorizes sub_event_type based on the presence of violence 
# at the protest; "Peaceful Protest" is the only definitively non-violent 
# category.

count_violent <- acled_modeling %>%
  filter(violence == TRUE) %>%  
  group_by(county) %>%
  summarize(number_violent = n(), .groups = "drop")

count_protests <- acled_modeling %>%
  group_by(county) %>%
  summarize(number_protests = n(), .groups = "drop")

model_violence <- full_join(count_violent, count_protests, by = "county") %>%
  mutate(number_violent = as.numeric(number_violent),
         number_protests = as.numeric(number_protests))

# There is certainly a more elegant way to count the number of violent protest
# and the number of total protests by county, but this was the only way I knew.

model_violence[is.na(model_violence)] <- 0

# Turned NA values in model_violence to 0's to reflect the fact that when the 
# number of violent protests was a NA value, this actually meant zero violent 
# protests had occurred. 
  
model_violence <- model_violence %>%
  mutate(proportion_violent = number_violent / number_protests,
         violence = ifelse(proportion_violent == 0,
                                      yes = FALSE,
                                      no = TRUE)) %>%
  select(!violence) %>%
  mutate(county = tolower(county))

# I changed the county names to be all lowercase to account for inconsistencies
# in capitalization in different datasets that I read in later.
```

Function for Inputting New Parameters from Census Data
```{r}
census_formatting <- function(ds){
  
  # Because I was inputting five unique datasets from the Census Bureau, I 
  # decided to write a function to simplify the process of cleaning these
  # datasets, which are all formatted in a similar way.
  
  # Data from the Census Bureau formatted county in a different way, so the 
  # following lines change the format of the values to be similar to the one
  # in the ACLED data. 

  ds_clean <- ds %>%
    separate(col = county, sep = ", ", into = c("county", "state")) %>%
    mutate(problem = ifelse(county %in% c("Baltimore city",
                                        "St. Louis city",
                                        "Roanoke city"), 
                            yes = TRUE, no = FALSE))
  
  # Baltimore, St. Louis, and Roanoke are unique in that they each include a 
  # separate county and city, so I needed to ensure that the word "city"
  # remained in the county name. 
  
  ds_clean %>%
    mutate(county = ifelse(problem == FALSE, 
                           yes = sub(ds_clean$county,
                                     pattern = " [[:alpha:]]*$",
                                     replacement = ""),
                           no = ds_clean$county)) %>%
    
    # The sub() function deletes the final word in each county name. Typically 
    # this means transforming something like "Queens County" to just "Queens."
    
    transform(county = paste(county, state, sep = ", ")) %>%
    select(!c(state, problem))
}

```

Census Bureau Data
```{r}
# The following chunks of code clean and format data from the Census Bureau
# using the census_formatting() function that was just created. Each chunk
# results in a two column tibble: one column is district and the other is the 
# variable that the dataset focuses on. I leave comments for only the first
# dataset, with the assumptions that the rest follow the same pattern. 

gini <- read_csv("raw_data/census_gini.csv", skip = 1, col_types = cols(
  .default = col_character()
)) %>%
  
  # The first row is simply a repetition of the column name, so it is deleted.
  
  clean_names() %>%
  rename("county" = geographic_area_name, 
         "gini_score" = estimate_gini_index) %>%
  select(county, gini_score) %>%
  census_formatting() %>%
  mutate(gini_score = as.numeric(gini_score))

poverty <- read_csv("raw_data/census_poverty.csv", skip = 1, col_types = cols(
  .default = col_character()
)) %>%
  clean_names() %>%
  select(estimate_percent_below_poverty_level_population_for_whom_poverty_status_is_determined,
         geographic_area_name) %>%
  rename("poverty" = estimate_percent_below_poverty_level_population_for_whom_poverty_status_is_determined,
         "county" = geographic_area_name) %>%
  mutate(poverty = as.numeric(poverty)) %>%
  census_formatting()

income <- read_csv("raw_data/census_income.csv", skip = 1, col_types = cols(
  .default = col_character()
)) %>%
  clean_names() %>%
  select(geographic_area_name, estimate_households_median_income_dollars) %>%
  rename("income" = estimate_households_median_income_dollars,
         "county" = geographic_area_name) %>%
  mutate(income = as.numeric(income)) %>%
  census_formatting()

population <- read_csv("raw_data/census_population.csv", skip = 1, 
                       col_types = cols(
  .default = col_character()
)) %>%
  clean_names() %>%
  select(geographic_area_name, estimate_total) %>%
  rename("population" = estimate_total,
         "county" = geographic_area_name) %>%
  mutate(population = as.numeric(population)) %>%
  census_formatting()

unemployment <- read_csv("raw_data/census_unemployment.csv", skip = 1, 
                         col_types = cols(
  .default = col_character()
)) %>%
  clean_names() %>%
  select(estimate_unemployment_rate_population_16_years_and_over, geographic_area_name,
         estimate_total_educational_attainment_population_25_to_64_years_less_than_high_school_graduate,
         estimate_total_educational_attainment_population_25_to_64_years) %>%
  rename("unemployment" = estimate_unemployment_rate_population_16_years_and_over,
         "less_than_hs" = estimate_total_educational_attainment_population_25_to_64_years_less_than_high_school_graduate,
         "edu_pop" = estimate_total_educational_attainment_population_25_to_64_years,
         "county" = geographic_area_name) %>%
  mutate("unemployment" = as.numeric(unemployment),
         "less_than_hs" = as.numeric(less_than_hs),
         "edu_pop" = as.numeric(edu_pop)) %>%
  census_formatting()

education <- unemployment %>%
  mutate(percent_less_than_hs = (less_than_hs/edu_pop)*100) %>%
  select(percent_less_than_hs, county)

census_data <- inner_join(education, gini, by = "county") %>%
  inner_join(income, by = "county") %>%
  inner_join(population, by = "county") %>%
  inner_join(poverty, by = "county") %>%
  inner_join(unemployment, by = "county") %>%
  mutate(county = tolower(county))

# I combine all the data from the Census Bureau into one dataset.

```

Police Killings Data
```{r}
states <- tibble(state_name = state.name) %>%
  bind_cols(tibble(state = state.abb))

police_killings <- read_excel("raw_data/police_killings.xlsx") %>%
  left_join(states, by = "state") %>%
  select(!state) %>%
  rename("state" = state_name,
         "county" = county) %>%
  
  # I read in a dataset with state names and state abbreviations, because the 
  # police killings datasets uses state abbreviations while the ACLED dataset
  # uses full names. To standardize the county names (state is included in the
  # county name), I changed the abbreviations to full names. 
  
  drop_na() %>%
  transform(county = paste(county, state, sep=", ")) %>%
  group_by(county) %>%
  summarize(police_killings = n(), .groups = "drop") %>%
  mutate(county = tolower(county))
```

County Health Data
```{r}
health_1 <- read_excel("raw_data/ranked_measure_data.xlsx", 
                                  skip = 1) %>%
  clean_names() %>%
  drop_na(county) %>%
  transform(county = paste(county, state, sep = ", ")) %>%
  rename("premature_death_rate" = years_of_potential_life_lost_rate,
         "housing_problems" = percent_severe_housing_problems) %>%
  select(county, premature_death_rate, teen_birth_rate, 
         preventable_hospitalization_rate, high_school_graduation_rate, 
         violent_crime_rate, housing_problems)

# The health data comes in two separate spreadsheets, hence health_1 and 
# health_2. I select the columns with variables that I think could be 
# interesting. I also reformat the county values to match my existing county 
# values. 

health_2 <- read_excel("raw_data/health_cont.xlsx", 
                                  skip = 1) %>%
  clean_names() %>%
  rename("physical_distress" = percent_frequent_physical_distress,
         "mental_distress" = percent_frequent_mental_distress) %>%
  drop_na(county) %>%
  transform(county = paste(county, state, sep = ", ")) %>%
  select(county, physical_distress, mental_distress, life_expectancy, 
         segregation_index, segregation_index_2, percent_homeowners, 
         percent_black, percent_non_hispanic_white, percent_hispanic, 
         homicide_rate, firearm_fatalities_rate)

# I repeat the same process for health_2 as it is formatted in the same way as
# health_1. 

health <- inner_join(health_1, health_2, by = "county") %>%
  mutate(county = tolower(county))
```

Full Dataset for Modeling: All Parameters, ACLED Data
```{r}
model <- left_join(health, police_killings, by = "county") %>%
  left_join(model_violence, by = "county") %>%
  left_join(census_data, by = "county") %>%
  mutate(percent_black_hispanic = percent_black + percent_hispanic,
         number_protests = ifelse(is.na(number_protests), yes = 0, 
                                  no = number_protests),
         number_violent = ifelse(is.na(number_violent), yes = 0, 
                                 no = number_violent),
         police_killings = ifelse(is.na(police_killings), yes = 0, 
                                  no = police_killings),
         teen_birth_rate = teen_birth_rate / 10)

# I join together all of the datasets with the different parameters I would 
# like to use in my model, in addition to the ACLED data for modeling violent 
# protests by county. 
```

Model: Fit
```{r}
fit_all <- stan_glm(data = model,
                    formula = number_violent ~ teen_birth_rate + housing_problems + 
                      physical_distress + mental_distress + segregation_index_2 + 
                      police_killings + gini_score + number_protests + 
                      poverty + percent_black_hispanic, 
                    refresh = 0)

# This model uses a formula that looks at the number of violent protests 
# (number_violent) based on other parameters from the "model" tibble.
```

Table of Results
```{r}
tbl_regression(fit_all, intercept = TRUE, 
               estimate_fun = function(x) style_sigfig(x, digits = 3)) %>%
  as_gt() %>%
  gt::tab_header(title = "Regression of Violent Protest Occurrence")

# This helps create the table of results that can be used in my ShinyApp. The
# estimate_fun function is used to increase the number of digits that show up
# for the median and 95% confidence interval.

```

General Protest Info
```{r}
blm_terms <- c("BLM", "NAACP", "African American", "African", "Black")
labor_terms <- c("Federation", "Union", "Labor", "Labour", "Worker", "AFL")
antifa_terms <- c("Antifa", "antifa", "Anti Facist")
militia_terms <- c("Militia", "Patriot", "Proud Boy", "Boogaloo", "KKK", 
                   "QAnon")
pro_police_terms <- c("Pro-Police", "Pro Police", "Blue")
republican_terms <- c("Republican", "GOP")
democrat_terms <- c("Dem", "Democrat")

# The ACLED dataset lists key actors/orgs at protests. Because it wouldn't
# neccessarily make sense to create a separate category for each of the many 
# different actors, I went through each of the different actors and
# categorized them into seven main categories. I focused on four of these 
# seven for subsequent visualizations because they tend to have a larger pool
# of protests. 

acled_w_subjects <- acled_data_new %>%
  mutate(blm = ifelse(str_detect(assoc_actor_1, 
                                 paste(blm_terms, collapse = '|')), 
                      yes = TRUE, no = FALSE),
         labor = ifelse(str_detect(assoc_actor_1, 
                                   paste(labor_terms, collapse = '|')), 
                      yes = TRUE, no = FALSE),
         antifa = ifelse(str_detect(assoc_actor_1, 
                                   paste(antifa_terms, collapse = '|')), 
                      yes = TRUE, no = FALSE),
         militia = ifelse(str_detect(assoc_actor_1, 
                                   paste(militia_terms, collapse = '|')), 
                      yes = TRUE, no = FALSE),
         pro_police = ifelse(str_detect(assoc_actor_1, 
                                   paste(pro_police_terms, collapse = '|')), 
                      yes = TRUE, no = FALSE),
         republican = ifelse(str_detect(assoc_actor_1, 
                                   paste(republican_terms, collapse = '|')), 
                      yes = TRUE, no = FALSE),
         democrat = ifelse(str_detect(assoc_actor_1, 
                                   paste(democrat_terms, collapse = '|')), 
                      yes = TRUE, no = FALSE),
         unknown = ifelse(is.na(assoc_actor_1), yes = TRUE, no = FALSE),
         all_actors = TRUE,
         all_violence = TRUE) %>%
  
  # I created a column for each of the seven major groups and used str_detect
  # to see if there were any occurrences of the actors that I grouped into 
  # each category. If str_detect found one of the actors for a specific
  # category in the actors list of a protest, it set the column as TRUE. 
  
  pivot_longer(cols = blm:democrat,
               names_to = "subject",
               values_to = "group_boolean")

# pivot_longer() is used simply for ease in plotting these values in a 
# ggplot. 
```

Mapping: Leaflet
```{r}
rural <- get_decennial(geography = "state",
                       variables = c("P001001", "P002005"),
                       year = 2010,
                       output = "wide",
                       geometry = TRUE) %>%
  rename(state = NAME) %>%
  mutate(prop_rural = P002005/P001001,
         state = reorder(state, prop_rural))

# This sets up the map that leaflet will use to create the map with all
# ACLED protests. 
```
