---
title: "Outtakes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This document contains code that is not needed in the data_gathering.Rmd file.

Violence -- BLM vs All Protests
```{r}
violence <- acled_data %>%
  select(sub_event_type) %>%
  mutate(sub_event_type = as.factor(sub_event_type)) %>%
  filter(sub_event_type == c("Peaceful protest", "Protest with intervention",
                            "Excessive force against protesters",
                            "Violent demonstration",
                            "Mob violence")) %>%
  group_by(sub_event_type) %>%
  summarize(count = n())

violence_BLM <- acled_data %>%
  filter(assoc_actor_1 == "BLM: Black Lives Matter") %>%
  select(sub_event_type) %>%
  mutate(sub_event_type = as.factor(sub_event_type)) %>%
  filter(sub_event_type == c("Peaceful protest", "Protest with intervention",
                            "Excessive force against protesters",
                            "Violent demonstration",
                            "Mob violence")) %>%
  group_by(sub_event_type) %>%
  summarize(count = n(), .groups = "drop")

comparison <- inner_join(violence, violence_BLM, by = "sub_event_type") %>%
  rename(all = count.x,
         blm = count.y) %>%
  pivot_longer(cols = all:blm,
               names_to = "type",
               values_to = "count")

ggplot(comparison, aes(x = reorder(sub_event_type, count), 
                       y = count, fill = type)) +
    geom_col(position = "identity") + 
    labs(title = "Violence at Protests",
         subtitle = "Summer and Fall 2020",
         x = "Type of Protest",
         y = "Number of Protests") + 
    coord_flip() + 
    scale_color_manual(breaks = c("all", "blm"),
                       labels = c("All Protests", "BLM")) + 
    theme_classic()
  
```

Data Gathering
```{r}
acled_data_new <- acled_data %>%
  select(-c(iso, event_id_cnty, event_id_no_cnty, year, time_precision, region, 
            country, admin3, geo_precision, source_scale, source)) %>%
  mutate(assoc_actor_1 = as.character(assoc_actor_1)) %>%
  mutate(blm = ifelse(str_detect(assoc_actor_1, 
                                 regex(c("BLM", "NAACP", "African American"), 
                                       ignore_case = TRUE)), 
                      yes = TRUE, no = FALSE)) %>%
  filter(blm == TRUE)
```

Plotting Violence by Protest Subject
```{r}
# regular
acled_data_new %>%
  filter(sub_event_type %in% c("Peaceful protest", "Protest with intervention",
                               "Violent demonstration", "Mob violence")) %>%
  filter(blm == TRUE) %>%
  select(sub_event_type, blm) %>%
  group_by(sub_event_type) %>%
  summarize(count = n(), .groups = "drop") %>%
  ggplot(aes(x = factor(sub_event_type, levels = c("Mob violence",
                                                   "Violent demonstration",
                                                   "Protest with intervention",
                                                   "Peaceful protest")), 
             y = count)) + 
    geom_col() + 
    labs(title = "Violence during Protests",
         subtitle = "Summer and Fall 2020",
         x = "Type of Protest",
         y = "Number of Protests") +
    scale_x_discrete(drop = FALSE) + 
    coord_flip() + 
    theme_classic()

# function w input ps
violence_plot <- function(ps){
  acled_data_new %>%
  filter(sub_event_type %in% c("Peaceful protest", "Protest with intervention",
                               "Violent demonstration", "Mob violence")) %>%
  filter({{ps}} == TRUE) %>%
  select(sub_event_type, {{ps}}) %>%
  group_by(sub_event_type) %>%
  summarize(count = n(), .groups = "drop") %>%
  ggplot(aes(x = factor(sub_event_type, levels = c("Mob violence",
                                                   "Violent demonstration",
                                                   "Protest with intervention",
                                                   "Peaceful protest")), 
             y = count)) + 
    geom_col() + 
    labs(title = "Violence during Protests",
         subtitle = "Summer and Fall 2020",
         x = "Type of Protest",
         y = "Number of Protests") +
    scale_x_discrete(drop = FALSE) + 
    coord_flip() + 
    theme_classic()
}
violence_plot(militia)
```

Ideology Dataset + Others
```{r}
# ideology
ideology <- read_csv("raw_data/ideology.csv", col_types = cols(
  county_fips = col_double(),
  mrp_ideology_mean = col_double(),
  mrp_sd = col_double(),
  mrp_lower = col_double(),
  mrp_upper = col_double(),
  raw_ideology_mean = col_double(),
  sample_size = col_double(),
  abb = col_character(),
  state_fips = col_double(),
  county_name = col_character(),
  population_2010 = col_character(),
  state = col_character(),
  obama_pc_t2012 = col_double(),
  romney_pct_2012 = col_character(),
  other_pct_2012 = col_character(),
  obama_pct_2008 = col_double(),
  mccain_pct_2008 = col_character(),
  other_pct_2008 = col_character()
)) %>%
  select(mrp_ideology_mean, county_name) %>%
  rename("NAME" = county_name,
         "ideology" = mrp_ideology_mean)
ideology_final <- district_formatting(ideology)

# mobility
mobility <- read_csv("raw_data/mobility.csv", col_types = cols(
  cty = col_character(),
  Name = col_character(),
  Household_Income_rP_gP_p25 = col_double()
)) %>%
  rename("district" = Name) %>%
  separate(col = district, sep = ", ", into = c("district", "state")) %>%
  left_join(states, by = "state") %>%
  select(!state) %>%
  rename("state" = state_name)

mobility_final <- mobility %>%
  mutate(district = sub(mobility$district, pattern = " [[:alpha:]]*$", 
                        replacement = "")) %>%
  transform(district = paste(district, state, sep=", ")) %>%
  select(Household_Income_rP_gP_p25, district) %>%
  rename("mobility" = Household_Income_rP_gP_p25)

# police killings
states <- tibble(state_name = state.name) %>%
  bind_cols(tibble(state = state.abb))
police_killings_final <- read_excel("raw_data/police_killings.xlsx") %>%
  left_join(states, by = "state") %>%
  select(!state) %>%
  rename("state" = state_name,
         "district" = county) %>%
  drop_na() %>%
  transform(district = paste(district, state, sep=", ")) %>%
  group_by(district) %>%
  summarize(police_killings = n(), .groups = "drop")
```


First District Formatting Function
```{r}
district_formatting <- function(ds){
  ds_clean <- ds[-1 ,] %>%
    rename("district" = NAME) %>%
    separate(col = district, sep = ", ", into = c("district", "state"))
  correct_district <- ds_clean %>%
    mutate(district = sub(ds_clean$district, pattern = " [[:alpha:]]*$", 
                        replacement = "")) %>%
    transform(district = paste(district, state, sep=", ")) %>%
    select(!state)
  return(correct_district)
}
```

Workflow
```{r}
data_split <- initial_split(data, prob = 0.80)
data_train <- training(data_split)
data_test <- testing(data_split)

data_wfl <- workflow() %>%
  add_recipe(recipe(data = data_train,
                    formula = number_violent ~ gini_score + prop_less_than_hs + 
                      police_killings + ideology + teen_birth_rate + 
                      high_school_graduation_rate + violent_crime_rate + 
                      housing_problems + physical_distress + 
                      life_expectancy + segregation_index_2 + 
                      percent_homeowners + number_protests)) %>%
  add_model(linear_reg() %>% 
              set_engine("lm"))

prediction_results <- data_wfl %>%
  fit(data = data_train) %>%
  predict(new_data = data_test) %>%
  bind_cols(data_test %>%
              select(number_violent)) %>%
  metrics(truth = number_violent, estimate = `.pred`)
```

Modeling: Income Inequality
```{r}
model_violence_gini <- model_violence %>%
  left_join(gini_final, by = "district") %>%
  select(district, violence, gini_score, proportion_violent)

fit_obj_gini <- stan_glm(data = model_violence_gini,
                    proportion_violent ~ gini_score - 1,
                    refresh = 0)

new_obs_gini <- tibble(gini_score = c(0.3288, 0.4238, 0.4489, 0.6592))

pp_gini <- posterior_predict(fit_obj_gini, newdata = new_obs_gini) %>%
  as_tibble() %>%
  mutate_all(as.numeric) %>%
  rename("min" = `1`,
         "low" = `2`,
         "high" = `3`,
         "max" = `4`) %>%
  pivot_longer(cols = min:max,
               names_to = "gini",
               values_to = "proportion_violent")

pp_gini_mean <- pp_gini %>%
  group_by(gini) %>%
  summarize(mean_violence = mean(proportion_violent), .groups = "drop") %>%
  arrange(mean_violence)

pp_gini_mean$mean_violence

ggplot(pp_gini, aes(x = proportion_violent, fill = gini)) +
  geom_histogram(aes(y = after_stat(count/sum(count))), bins = 75,
                 color = "white", position = "identity", alpha = 0.5) +
  geom_vline(xintercept = pp_gini_mean$mean_violence[1]) +
  geom_vline(xintercept = pp_gini_mean$mean_violence[2]) +
  geom_vline(xintercept = pp_gini_mean$mean_violence[3]) +
  geom_vline(xintercept = pp_gini_mean$mean_violence[4]) +
  scale_y_continuous(labels = scales::percent_format()) + 
  labs(title = "Posterior Distribution for Violence based on Gini",
       x = "Proportion Violent",
       y = "Probability") +
  theme_bw()

```

Modeling: Poverty
```{r}
model_violence_poverty <- model_violence %>%
  left_join(poverty_final, by = "district") %>%
  select(district, violence, poverty, proportion_violent) %>%
  drop_na(poverty)

fit_obj_poverty <- stan_glm(data = model_violence_poverty,
                    proportion_violent ~ poverty - 1,
                    refresh = 0)

quantile(model_violence_poverty$poverty)

new_obs_poverty <- tibble(poverty = c(8.7, 15.5))

pp_poverty <- posterior_predict(fit_obj_poverty, newdata = new_obs_poverty) %>%
  as_tibble() %>%
  mutate_all(as.numeric) %>%
  rename("low" = `1`,
         "high" = `2`) %>%
  pivot_longer(cols = low:high,
               names_to = "poverty",
               values_to = "proportion_violent")

ggplot(pp_poverty, aes(x = proportion_violent, fill = poverty)) +
  geom_histogram(aes(y = after_stat(count/sum(count))), bins = 75,
                 color = "white", position = "identity", alpha = 0.5) +
  scale_y_continuous(labels = scales::percent_format()) + 
  labs(title = "Posterior Distribution for Poverty Rate",
       x = "Poverty Rate",
       y = "Probability") +
  theme_bw()

```

Modeling: Income
```{r}
model_violence_income <- model_violence %>%
  left_join(income_final, by = "district") %>%
  select(district, violence, income, proportion_violent) %>%
  drop_na(income)

fit_obj_income <- stan_glm(data = model_violence_income,
                    proportion_violent ~ income - 1,
                    refresh = 0)

new_obs_income <- tibble(income = c(53518, 72736))

pp_income <- posterior_predict(fit_obj_income, newdata = new_obs_income) %>%
  as_tibble() %>%
  mutate_all(as.numeric) %>%
  rename("low" = `1`,
         "high" = `2`) %>%
  pivot_longer(cols = low:high,
               names_to = "income",
               values_to = "proportion_violent")

ggplot(pp_income, aes(x = proportion_violent, fill = income)) +
  geom_histogram(aes(y = after_stat(count/sum(count))), bins = 75,
                 color = "white", position = "identity", alpha = 0.5) +
  scale_y_continuous(labels = scales::percent_format()) + 
  labs(title = "Posterior Distribution for Violence based on Income",
       x = "Proportion Violent",
       y = "Probability") +
  theme_bw()

```

Model: Posterior
```{r}
new_obs <- tibble(number_protests = 7,
                                  gini_score = 0.9,
                                  poverty = 80,
                                  housing_problems = 13.87,
                                  physical_distress = 12.13,
                                  mental_distress = 12.99,
                                  segregation_index_2 = 30.81,
                                  police_killings = 2.7,
                                  percent_black_hispanic = 18.67,
                                  teen_birth_rate = 2.98)

new_obs_default <- tibble(number_protests = 4.89,
                  gini_score = 0.45,
                  poverty = 12.41,
                  housing_problems = 13.87,
                  physical_distress = 12.13,
                  mental_distress = 12.99,
                  segregation_index_2 = 30.81,
                  police_killings = 2.7,
                  percent_black_hispanic = 18.67,
                  teen_birth_rate = 2.98)

default <- posterior_predict(fit_all, newdata = new_obs_default) %>%
  as_tibble() %>%
  mutate_all(as.numeric) %>%
  rename("default" = `1`)

new <- posterior_predict(fit_all, newdata = new_obs) %>%
  as_tibble() %>%
  mutate_all(as.numeric) %>%
  rename("new" = `1`)

full <- default %>%
  bind_cols(new) %>%
  pivot_longer(cols = default:new,
               names_to = "pp_results",
               values_to = "number_violent")

full %>%
  ggplot(aes(x = number_violent, fill = pp_results)) +
    geom_histogram(aes(y = after_stat(count/sum(count))), bins = 75,
                           color = "white", position = "identity", alpha = 0.6) +
    scale_y_continuous(labels = scales::percent_format()) + 
    xlim(c(-10,20)) +
    labs(x = "Number of Violent Protests",
         y = "Probability",
         title = "Model: Number of Violent Protests \n in a Hypothetical County") +
    theme_economist() + 
    theme(title = element_text(size = 10), 
          legend.text = element_text(size = 10),
          axis.text.y = element_text(size = 8),
          axis.text.x = element_text(size = 8),
          axis.title.x = element_text(size = 10, face = "bold"),
          axis.title.y = element_text(size = 10, face = "bold"),
          panel.background = element_rect(fill = "white"), 
          plot.background = element_rect(fill = "white")) +
    scale_fill_manual(name = "", 
                      breaks = c("default", "new"),
                      labels = c("Average County", "Hypothetical County"),
                      values = c("#00798c", "#d1495b"))
```


ACLED with subjects plot
```{r}
acled_w_subjects %>%
  filter(sub_event_type %in% c("Peaceful protest", "Protest with intervention",
                                             "Violent demonstration", "Mob violence")) %>%
  filter(subject == "blm" & group_boolean == TRUE) %>%
  select(sub_event_type) %>%
  group_by(sub_event_type) %>%
  summarize(count = n(), .groups = "drop") %>%
  ggplot(aes(x = factor(sub_event_type, levels = c("Mob violence",
                                                   "Violent demonstration",
                                                   "Protest with intervention",
                                                   "Peaceful protest")), 
                           y = count)) + 
                geom_col(fill = "#00798c", color = "white", alpha = 0.7) + 
                labs(title = "Violence during Protests",
                     subtitle = "Summer and Fall 2020",
                     x = "Type of Protest",
                     y = "Number of Protests") +
                scale_x_discrete(drop = FALSE, breaks = c("Mob violence",
                                                   "Violent demonstration",
                                                   "Protest with intervention",
                                                   "Peaceful protest"),
                                 labels = c("Mob \n violence",
                                                   "Violent \n demonstration",
                                                   "Protest with \n intervention",
                                                   "Peaceful \n protest")) + 
                theme_economist() + 
                coord_flip() + 
                theme(axis.text.y = element_text(size = 8, hjust = 1),
                      axis.text.x = element_text(size = 8),
                      axis.title.x = element_text(size = 12, face = "bold",
                                                  vjust = -1),
                      axis.title.y = element_text(size = 12, face = "bold",
                                                  vjust = 4),
                      panel.background = element_rect(fill = "white"), 
                      plot.background = element_rect(fill = "white"))
```

Mapping: Leaflet
```{r}
rural <- get_decennial(geography = "state",
                       variables = c("P001001", "P002005"),
                       year = 2010,
                       output = "wide",
                       geometry = TRUE) %>%
  rename(state = NAME) %>%
  mutate(prop_rural = P002005/P001001,
         state = reorder(state, prop_rural))

# This sets up the map that leaflet will use to create the map with all
# ACLED protests. 

subset <- acled_data_new %>%
  mutate(event_date = ymd(event_date)) %>%
  filter(event_date <= "2020-05-30")

map <- leaflet(rural) %>%
  addTiles() %>%
  addCircles(lng = subset$longitude, lat = subset$latitude, radius = 0.1, color = "navy")
```